name: GCP login
description: "Login to GCP & configure gcloud CLI."
inputs:
  gcp_service_account_json:
    description: 'Service account with permissions to create Constellation on GCP.'
    required: true
runs:
  using: 'composite'
  steps:
  # As described at:
  # https://github.com/google-github-actions/setup-gcloud#service-account-key-json
  - name: Authorize GCP access
    uses: google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955
    with:
      credentials_json: ${{ inputs.gcp_service_account_json }}
  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb
  - name: Verify logged in
    run: gcloud info
    shell: bash
