run:
  timeout: 5m

output:
  format: tab
  sort-results: true
  build-tags:
    - integration
    - aws
    - gcp

linters:
  enable:
    # Default linters
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Additional linters
    - bodyclose
    - errname
    - exportloopref
    - ifshort
    - godot
    - gofmt
    - gofumpt
    - misspell
    - noctx
    - tenv
    - unconvert
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 20

linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (*go.uber.org/zap.Logger).Sync
      - (*google.golang.org/grpc.Server).Serve
