name: Build disk-mapper
description: Build the Constellation disk-mapper binary

inputs:
  outputPath:
    description: 'Output path of the binary'
    default: './disk-mapper'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6

    - name: Install Dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install cmake make
    
    - name: Build the disk-mapper
      shell: bash
      run: |
        mkdir -p build && cd build
        cmake ..
        make disk-mapper
        mv -n disk-mapper "${{ inputs.outputPath }}"
