apiVersion: v2
name: constellation-services
description: A chart to deploy all microservices that are part of a valid constellation cluster
type: application
version: 1.2.8
dependencies:
  - name: keyservice
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
      - QEMU
  - name: join-service
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
      - QEMU
  - name: ccm
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
  - name: cnm
    version: 1.2.8
    tags:
      - Azure
  - name: autoscaler
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
  - name: verification-service
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
      - QEMU
  - name: konnectivity
    version: 1.2.8
    tags:
      - Azure
      - GCP
      - AWS
      - QEMU
  - name: gcp-guest-agent
    version: 1.2.8
    tags:
      - GCP
  - name: gcp-compute-persistent-disk-csi-driver
    version: 1.0.1
    condition: gcp.deployCSIDriver
    tags:
      - GCP
  - name: azuredisk-csi-driver
    version: 1.0.1
    condition: azure.deployCSIDriver
    tags:
      - Azure
