# permissions for end users to edit autoscalingstrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscalingstrategy-editor-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/status
  verbs:
  - get
