# permissions for end users to view autoscalingstrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscalingstrategy-viewer-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/status
  verbs:
  - get
