# permissions for end users to view nodeimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeimage-viewer-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/status
  verbs:
  - get
