# permissions for end users to edit nodeimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeimage-editor-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/status
  verbs:
  - get
