# permissions for end users to edit pendingnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pendingnode-editor-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes/status
  verbs:
  - get
