# permissions for end users to view pendingnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pendingnode-viewer-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes/status
  verbs:
  - get
