---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - pendingnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups/status
  verbs:
  - get
  - patch
  - update
