---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - autoscalingstrategies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/finalizers
  verbs:
  - update
- apiGroups:
  - update.edgeless.systems
  resources:
  - nodeimages/status
  verbs:
  - get
  - patch
  - update
