# permissions for end users to edit scalinggroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalinggroup-editor-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups/status
  verbs:
  - get
