# permissions for end users to view scalinggroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalinggroup-viewer-role
rules:
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.edgeless.systems
  resources:
  - scalinggroups/status
  verbs:
  - get
