name: Build micro service (KO)
description: Build and upload a container image for a Constellation micro-service
inputs:
  name:
    description: "Name of the micro-service"
    required: true
  koConfig:
    description: "Path to the .ko.yaml config file"
    required: true
  koTarget:
    description: "Go package to build with ko"
    required: true
  pushTag:
    description: "Use this image tag"
    required: false
  githubToken:
    description: "GitHub authorization token"
    required: true

# Linux runner only
runs:
  using: "composite"
  steps:
    - name: Determine pseudo version
      id: pseudo-version
      uses: ./.github/actions/pseudo_version

    - name: Set up ko
      uses: imjasonh/setup-ko@v0.6

    - name: Build and upload ko container image
      shell: bash
      id: build
      env:
        KO_USER: ${{ github.actor }}
        KO_CONFIG_PATH: ${{ inputs.koConfig }}
        KO_PASSWORD: ${{ inputs.githubToken }}
        KO_DOCKER_REPO: ${{ env.REGISTRY }}/edgelesssys/${{ inputs.name }}-ko
      run: |
        tags=""
        if [ "${{ github.ref }}" == "${{ github.event.repository.default_branch }}" ]; then
          tags="latest"
        else:
          tags="${{ github.sha }}"
        fi

        if [ -n "${{ inputs.pushTag }}" ]; then
          if [ -n "${tags}" ]; then
            tags="${tags},${{ inputs.pushTag }}"
          else
            tags="${{ inputs.pushTag }}"
          fi
        fi

        if [ -n "${{ steps.pseudo-version.outputs.pseudoVersion }}" ]; then
          if [ -n "${tags}" ]; then
            tags="${tags},${{ steps.pseudo-version.outputs.pseudoVersion }}"
          else
            tags="${{ steps.pseudo-version.outputs.pseudoVersion }}"
          fi
        fi

        ko build ${{ inputs.koTarget }} --bare --tags ${tags}
