name: Build and Upload CoreOS
env:
  REGISTRY: ghcr.io
  AZ_CLI_VERSION: 2.37.0
on:
  workflow_dispatch:
    inputs:
      bootstrapper-name:
        description: bootstrapper name
        required: true
        type: string

  workflow_call:
    inputs:
      bootstrapper-name:
        required: true
        type: string

    secrets:
      CI_GITHUB_REPOSITORY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      BUCKET_NAME:
        required: true
      PUBLIC_BUCKET_NAME:
        required: true
      AZURE_CREDENTIALS:
        required: true

jobs:
  build-coreos:
    name: "Build CoreOS using customized COSA"
    runs-on: [self-hosted, linux, nested-virt]
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        shell: bash
    env:
      working-directory: ${{ github.workspace }}/image
      SHELL: /bin/bash
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: recursive
          token: ${{ secrets.CI_GITHUB_REPOSITORY }}

      - name: Log in to the Container registry
        id: docker-login
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Install azure CLI"
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt-get install -y --allow-downgrades "azure-cli=${AZ_CLI_VERSION}-1~$(lsb_release -sc)"
          wget -q https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
          tar --strip-components 1 -xf azcopy.tar.gz
          rm azcopy.tar.gz
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Login to Azure
        uses: azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Go environment
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: "1.18"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libcryptsetup12 libcryptsetup-dev

      - name: "Compile disk-mapper"
        run: |
          mkdir -p ${{ github.workspace }}/build
          GOCACHE=/home/github-actions-runner-user/.cache/go-build GOPATH=/home/github-actions-runner-user/go GOPRIVATE=github.com/edgelesssys GOMODCACHE=/home/github-actions-runner-user/.cache/go-mod go build -o ${{ github.workspace }}/build/disk-mapper -ldflags "-s -w"
        working-directory: ${{ github.workspace }}/state/cmd

      - name: "Store GH token to be mounted by cosa"
        run: echo "machine github.com login api password ${{ secrets.CI_GITHUB_REPOSITORY }}" > /tmp/.netrc

      - name: "Set image timestamp"
        run: |
          TIMESTAMP=$(date +%s)
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_TIMESTAMP=constellation-coreos-${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=0.0.${TIMESTAMP}" >> $GITHUB_ENV

      - name: "Build and Upload"
        run: >
          make -j$(nproc) CONTAINER_ENGINE=docker NETRC=/tmp/.netrc GCP_IMAGE_NAME="${{ env.IMAGE_TIMESTAMP }}" AZURE_IMAGE_NAME="${{ env.IMAGE_TIMESTAMP }}"
          AZURE_IMAGE_DEFINITION="constellation-coreos" AZURE_IMAGE_VERSION="${{env.IMAGE_VERSION }}" DOWNLOAD_BOOTSTRAPPER=y BOOTSTRAPPER_URL="https://${{ secrets.PUBLIC_BUCKET_NAME }}.s3.us-east-2.amazonaws.com/bootstrapper/${{ inputs.bootstrapper-name }}"
          image-gcp image-azure upload-gcp upload-azure
        working-directory: ${{ env.working-directory }}
