name: Build and upload access-manager image
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: access-manager

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "access_manager/**"
      - "internal/deploy/**"

# Abort runs of *this* workflow, if a new commit with the same ref is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-access-manager:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v3

      - name: Build and upload access-manager container image
        id: build-and-upload
        uses: ./.github/actions/build_micro_service
        with:
          name: access-manager
          projectVersion: "0.0.0"
          dockerfile: access_manager/Dockerfile
          githubToken: ${{ secrets.GITHUB_TOKEN }}
