name: Build and Upload access-manager image
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: access-manager

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "access_manager/**"
      - "internal/deploy/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
      - name: Set up Docker Buildx
        id: docker-setup
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        id: docker-login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push constellation-access-manager container image
        id: build-constellation-access-manager
        uses: docker/build-push-action@v2
        with:
          context: .
          file: access_manager/Dockerfile
          target: release
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
