name: Build and upload KMS image
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kmsserver

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "kms/**"
      - "internal/constants/**"
      - "internal/file/**"

jobs:
  build-kms-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Build and upload KMS server container image
        id: build-and-upload
        uses: ./.github/actions/build_micro_service
        with:
          name: kmsserver
          projectVersion: '0.0.0'
          dockerfile: kms/Dockerfile
          githubToken: ${{ secrets.GITHUB_TOKEN }}
