name: Build and upload join-service image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "joinservice/**"
      - "internal/atls/**"
      - "internal/attestation/**"
      - "internal/constants/**"
      - "internal/file/**"
      - "internal/grpc/**"
      - "internal/oid/**"

# Abort runs of *this* workflow, if a new commit with the same ref is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-join-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Build and upload join-service container image
        id: build-and-upload
        uses: ./.github/actions/build_micro_service
        with:
          name: join-service
          projectVersion: '0.0.0'
          dockerfile: joinservice/Dockerfile
          githubToken: ${{ secrets.GITHUB_TOKEN }}
