name: Purge branch

on:
  delete:

permissions:
  contents: read

jobs:
  purge:
    name: Delete ref from versions API
    uses: ./.github/workflows/versionsapi.yml
    secrets: inherit
    with:
      command: remove
      rm_all: true
      ref: ${{ github.event.ref }}
