name: Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/edgelesssys/*
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.18"

      - name: Run Integration Test
        run: DEBUG=true go test -v -tags integration ./test/
