name: Etcd Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.18"

      - name: Test Constellation etcd integration
        run: go test -v --race -cover -count=3 -tags integration
        working-directory: coordinator/store
