name: Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# Abort runs of *this* workflow, if a new commit with the same ref is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/edgelesssys/*
      CTEST_OUTPUT_ON_FAILURE: True
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup Go environment
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: "1.18"
          cache: true

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libcryptsetup12 libcryptsetup-dev cmake

      - name: Create and populate build folder
        run: mkdir build && cd build && cmake ..

      # Runs all test targets starting with "integration-"
      - name: Integration Tests
        run: ctest -R integration-
        working-directory: build
