name: Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# Abort runs of *this* workflow, if a new commit with the same ref is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/edgelesssys/*
      CTEST_OUTPUT_ON_FAILURE: True
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.18"

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libcryptsetup12 libcryptsetup-dev cmake

      - name: Create and populate build folder
        run: mkdir build && cd build && cmake ..

      # Runs all test targets starting with "integration-"
      - name: Integration Tests
        run: ctest -R integration-
