name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/edgelesssys/*
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libcryptsetup12 libcryptsetup-dev

      - name: Test
        # https://github.com/golang/go/issues/50745
        run: go test -race -count=3 $(go list -f '{{.Dir}}/...' -m | xargs)
